version: "3.9"

services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-stack:/data

  redis-web:
    image: redis/redis-stack
    container_name: redis-web
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis-web:/data

volumes:
  postgres:
  redis-stack:
  redis-web:
