version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-stack:/data

  redis-web:
    image: redis/redis-stack
    container_name: redis-web
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis-web:/data

volumes:
  postgres:
  redis-stack:
  redis-web:
