version: "3.9"

services:
  psql:
    image: postgres
    container_name: psql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat_pdf
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-stack:/data

  redis-web:
    image: redis/redis-stack
    container_name: redis-web
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis-web:/data

volumes:
  pgdata:
  redis-stack:
  redis-web:
